services:
  backend:
    build:
      ./backend
    ports:
      - '8888:8888'

  frontend:
    build:
      ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    restart: always
    ports:
      - '3333:3333'