services:
  backend:
    build:
      ./backend
    ports:
      - '8888:8888'
    depends_on:
      - postgres
    restart: always

  frontend:
    build:
      ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    restart: always
    ports:
      - '3333:3333'

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
#    ports:
#      - '5432:5432'

volumes:
  postgres-data: